/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesCourseIdGroupsRouteImport } from './routes/courses/$courseId/groups'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdGroupsRoute = CoursesCourseIdGroupsRouteImport.update({
  id: '/courses/$courseId/groups',
  path: '/courses/$courseId/groups',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$courseId/groups': typeof CoursesCourseIdGroupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$courseId/groups': typeof CoursesCourseIdGroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/$courseId/groups': typeof CoursesCourseIdGroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses/$courseId/groups'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses/$courseId/groups'
  id: '__root__' | '/' | '/courses/$courseId/groups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesCourseIdGroupsRoute: typeof CoursesCourseIdGroupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/groups': {
      id: '/courses/$courseId/groups'
      path: '/courses/$courseId/groups'
      fullPath: '/courses/$courseId/groups'
      preLoaderRoute: typeof CoursesCourseIdGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesCourseIdGroupsRoute: CoursesCourseIdGroupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
